<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="ScissorHands.Plugin.GoogleAnalytics" />
    <PackageReference Include="ScissorHands.Plugin.OpenGraph" />
    <PackageReference Include="ScissorHands.Web" />
  </ItemGroup>

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);themes/**/bin/**;themes/**/obj/**</DefaultItemExcludes>
  </PropertyGroup>

</Project>
